name: Hadou-CAN CI

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: clone
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: login to docker.pkg.github.com
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: fetch container master
      run: docker pull docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:master || true

    - name: fetch container for branch
      run: docker pull docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:${GITHUB_REF##*/} || true

    - name: build container
      run: docker build --cache-from docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:${GITHUB_REF##*/} continuous_integration/build --file continuous_integration/build/Dockerfile --tag hadoucan-fw-tools

    - name: tag container
      run: docker tag hadoucan-fw-tools docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:${GITHUB_REF##*/}

    - name: push container
      run: docker push docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:${GITHUB_REF##*/}

    - name: build
      run: ./scripts/build_ci.sh

    - name: Upload debug artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hadoucan-fw-debug
        path: ${{ github.workspace }}/canusbfdiso-debug.tar.gz

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hadoucan-fw-release
        path: ${{ github.workspace }}/canusbfdiso-release.tar.gz
