name: Hadou-CAN CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu:18.04

    steps:
    - uses: actions/checkout@master
    - name: configure
      run: ./generate_cmake.sh
    - name: make
      run: make -C build/ram/release
