name: Hadou-CAN CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: clone
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: login to docker.pkg.github.com
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: fetch container
      run: docker pull docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:latest || true

    - name: build container
      run: docker build --cache-from docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:latest continuous_integration/build --file continuous_integration/build/Dockerfile --tag hadoucan-fw-tools

    - name: tag container
      run: docker tag hadoucan-fw-tools docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:latest

    - name: push container
      run: docker push docker.pkg.github.com/suburbanembedded/hadoucan-fw/hadoucan-fw-tools:latest

    - name: build
      run: ./scripts/build_ci.sh
