name: Hadou-CAN CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure
      run: ./generate_cmake.sh
    - name: make
      run: make -C build/ram/release
