name: Hadou-CAN CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cd $GITHUB_WORKSPACE && ./generate_cmake.sh
    - name: make
      run: make -C $GITHUB_WORKSPACE/build/ram/release
